# PURPOSE: Bind both native builds to the reviewed downstream core patch series.
# RESPONSIBILITY: Verify source identity, serialize preparation, and reject drift.
# DEPENDENCIES: CMake and Git; the exact initialized Valhalla submodule.
# CONSUMERS: src/CMakeLists.txt and isolated patch-gate regression tests.

find_package(Git REQUIRED)
get_filename_component(_valhalla_mobile_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)

function(_valhalla_git output directory)
  execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${directory}" ${ARGN}
    RESULT_VARIABLE result OUTPUT_VARIABLE value ERROR_VARIABLE error
    OUTPUT_STRIP_TRAILING_WHITESPACE)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "Valhalla patch gate: Git verification failed")
  endif()
  set("${output}" "${value}" PARENT_SCOPE)
endfunction()

# git apply writes each patch FILE argument separately, so a failure in a later patch would keep
# the earlier ones. One concatenated input is all-or-nothing, and a later patch may still touch a
# file an earlier one changed.
function(_valhalla_git_apply core series)
  execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${core}" apply ${ARGN} -
    INPUT_FILE "${series}" RESULT_VARIABLE result OUTPUT_QUIET ERROR_QUIET)
  if(NOT result EQUAL 0)
    file(REMOVE "${series}")
    message(FATAL_ERROR "Valhalla patch gate: Git verification failed")
  endif()
endfunction()

# Tracked edits are allowed only in the series' listed sources (passed as ARGN). Sets
# <output> to "" when clean, else to the failure message (callers decide how to fail).
function(_valhalla_core_problem output core)
  _valhalla_git(staged "${core}" diff --cached --name-only)
  _valhalla_git(changed "${core}" diff --name-only)
  _valhalla_git(metadata "${core}" diff --summary)
  _valhalla_git(untracked "${core}" ls-files --others --exclude-standard)
  set(problem "")
  if(NOT untracked STREQUAL "")
    set(problem "Valhalla patch gate: unexpected untracked core files")
  elseif(NOT staged STREQUAL "" OR NOT metadata STREQUAL "")
    set(problem "Valhalla patch gate: unexpected staged or file-mode changes")
  else()
    string(REPLACE "\n" ";" changed "${changed}")
    foreach(path IN LISTS changed)
      list(FIND ARGN "${path}" listed)
      if(listed EQUAL -1)
        set(problem "Valhalla patch gate: unexpected tracked core changes")
      endif()
    endforeach()
  endif()
  set("${output}" "${problem}" PARENT_SCOPE)
endfunction()

function(_valhalla_require_clean_core core)
  _valhalla_core_problem(problem "${core}" ${ARGN})
  if(NOT problem STREQUAL "")
    message(FATAL_ERROR "${problem}")
  endif()
endfunction()

# Sets <prefix>_original / <prefix>_patched to TRUE when every listed source has that hash.
function(_valhalla_source_state prefix core)
  set(all_original TRUE)
  set(all_patched TRUE)
  set(index 0)
  foreach(target IN LISTS targets)
    list(GET originals ${index} original)
    list(GET patcheds ${index} patched)
    # A listed source a patch deleted (or replaced by a symlink) is neither state; never hash it.
    if(EXISTS "${core}/${target}" AND NOT IS_SYMLINK "${core}/${target}")
      file(SHA256 "${core}/${target}" actual)
    else()
      set(actual "missing")
    endif()
    if(NOT actual STREQUAL original)
      set(all_original FALSE)
    endif()
    if(NOT actual STREQUAL patched)
      set(all_patched FALSE)
    endif()
    math(EXPR index "${index} + 1")
  endforeach()
  set("${prefix}_original" ${all_original} PARENT_SCOPE)
  set("${prefix}_patched" ${all_patched} PARENT_SCOPE)
endfunction()

function(_valhalla_prepare root)
  include("${root}/patches/valhalla/manifest.cmake")
  set(core "${root}/src/valhalla")
  list(LENGTH core_patches patch_fields)
  list(LENGTH core_sources source_fields)
  math(EXPR patch_odd "${patch_fields} % 2")
  math(EXPR source_odd "${source_fields} % 3")
  if(patch_fields EQUAL 0 OR source_fields EQUAL 0 OR
      NOT patch_odd EQUAL 0 OR NOT source_odd EQUAL 0)
    message(FATAL_ERROR "Valhalla patch gate: malformed patch manifest")
  endif()
  # The series is applied in manifest order.
  set(patches "")
  set(patch_shas "")
  math(EXPR last "${patch_fields} - 1")
  foreach(index RANGE 0 ${last} 2)
    math(EXPR next "${index} + 1")
    list(GET core_patches ${index} name)
    list(GET core_patches ${next} sha)
    list(APPEND patches "${root}/patches/valhalla/${name}")
    list(APPEND patch_shas "${sha}")
  endforeach()
  set(targets "")
  set(originals "")
  set(patcheds "")
  math(EXPR last "${source_fields} - 1")
  foreach(index RANGE 0 ${last} 3)
    math(EXPR second "${index} + 1")
    math(EXPR third "${index} + 2")
    list(GET core_sources ${index} target)
    list(GET core_sources ${second} original)
    list(GET core_sources ${third} patched)
    list(APPEND targets "${target}")
    list(APPEND originals "${original}")
    list(APPEND patcheds "${patched}")
  endforeach()
  if(NOT EXISTS "${core}/.git" OR IS_SYMLINK "${core}")
    message(FATAL_ERROR "Valhalla patch gate: initialized regular source and patch required")
  endif()
  foreach(target IN LISTS targets)
    if(NOT EXISTS "${core}/${target}" OR IS_SYMLINK "${core}/${target}")
      message(FATAL_ERROR "Valhalla patch gate: initialized regular source and patch required")
    endif()
  endforeach()
  foreach(patch IN LISTS patches)
    if(NOT EXISTS "${patch}" OR IS_SYMLINK "${patch}")
      message(FATAL_ERROR "Valhalla patch gate: initialized regular source and patch required")
    endif()
  endforeach()
  _valhalla_git(lock_path "${core}" rev-parse --git-path rods-core-patch.lock)
  get_filename_component(lock_path "${lock_path}" ABSOLUTE BASE_DIR "${core}")
  # Concurrent architecture configurations share this source tree.
  file(LOCK "${lock_path}" GUARD FUNCTION TIMEOUT 60 RESULT_VARIABLE lock_result)
  if(NOT lock_result STREQUAL "0")
    message(FATAL_ERROR "Valhalla patch gate: could not lock core preparation")
  endif()
  _valhalla_git(head "${core}" rev-parse HEAD)
  _valhalla_git(link "${root}" ls-tree HEAD -- src/valhalla)
  _valhalla_git(index "${root}" ls-files --stage -- src/valhalla)
  if(NOT head STREQUAL expected_core OR
      NOT link STREQUAL "160000 commit ${expected_core}\tsrc/valhalla" OR
      NOT index STREQUAL "160000 ${expected_core} 0\tsrc/valhalla")
    message(FATAL_ERROR "Valhalla patch gate: core HEAD or parent gitlink differs from reviewed pin")
  endif()
  _valhalla_require_clean_core("${core}" ${targets})
  set(index 0)
  foreach(patch IN LISTS patches)
    list(GET patch_shas ${index} sha)
    file(SHA256 "${patch}" actual_patch)
    if(NOT actual_patch STREQUAL sha)
      message(FATAL_ERROR "Valhalla patch gate: patch checksum mismatch")
    endif()
    math(EXPR index "${index} + 1")
  endforeach()
  _valhalla_source_state(state "${core}")
  if(state_original)
    # The series as one input inside the Git directory (held under the lock, never a core file).
    set(series "${lock_path}.series")
    file(WRITE "${series}" "")
    set(index 0)
    foreach(patch IN LISTS patches)
      file(READ "${patch}" text)
      # Re-check the bytes actually applied, not just the file hashed above.
      string(SHA256 actual_patch "${text}")
      list(GET patch_shas ${index} sha)
      if(NOT actual_patch STREQUAL sha)
        file(REMOVE "${series}")
        message(FATAL_ERROR "Valhalla patch gate: patch checksum mismatch")
      endif()
      file(APPEND "${series}" "${text}")
      math(EXPR index "${index} + 1")
    endforeach()
    _valhalla_git_apply("${core}" "${series}" --check)
    _valhalla_git_apply("${core}" "${series}")
    _valhalla_source_state(state "${core}")
    _valhalla_core_problem(problem "${core}" ${targets})
    # An applied series that is not exactly the reviewed result (a wrong manifest hash, a patch
    # touching an unlisted file) is reversed before failing: the core is left as it was found.
    if(NOT state_patched OR NOT problem STREQUAL "")
      _valhalla_git_apply("${core}" "${series}" -R)
      file(REMOVE "${series}")
      if(problem STREQUAL "")
        set(problem "Valhalla patch gate: core source checksum mismatch")
      endif()
      message(FATAL_ERROR "${problem}")
    endif()
    file(REMOVE "${series}")
  endif()
  # Accept only the fully patched series; a partial or foreign tree is never rewritten.
  if(NOT state_patched)
    message(FATAL_ERROR "Valhalla patch gate: core source checksum mismatch")
  endif()
  _valhalla_require_clean_core("${core}" ${targets})
  message(STATUS "Valhalla core: reviewed patch series verified")
  if(NOT CMAKE_SCRIPT_MODE_FILE)
    set(depends "${root}/patches/valhalla/manifest.cmake" ${patches})
    foreach(target IN LISTS targets)
      list(APPEND depends "${core}/${target}")
    endforeach()
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${depends})
  endif()
endfunction()

_valhalla_prepare("${_valhalla_mobile_root}")
